name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
  - cron: '0 0 * * *' # midnight UTC

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
        components: rustfmt

    - name: Install deps
      run: |
        sudo apt update
        sudo apt install --yes gcc pkg-config libssl-dev

    - name: Install cargo play
      run: cargo install cargo-play

    - name: Install cargo make
      run: cargo install cargo-make

    - name: Download the list and run tests
      run: cargo make test

    - name: Publish
      shell: bash
      run: |
        if ! git diff --exit-code --quiet data/rules.txt; then
                cargo doc --all-features
                git config --local user.email "actions@users.noreply.github.com"
                git config --local user.name "github-actions[bot]"
                git remote add upstream https://rushmorem:${{ secrets.GITHUB_TOKEN }}@github.com/addr-rs/psl.git
                git add data/rules.txt src/list.rs
                git commit -m 'update the list'
                cargo install --force --version 0.24.0 cargo-release
                cargo release patch --execute --no-confirm --push-remote upstream --token ${{ secrets.CRATES_TOKEN }}
        fi
